---
- name: Install node exporter
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo 
  tasks:
  
  - name: Update
    become: yes
    command: apt update

  - name: Install prometheus-node-exporter
    become: yes
    command: apt install prometheus-node-exporter -y

